# \u5e94\u7528\u7aef\u53e3\u914d\u7f6e
server:
  port: 82
spring:
  application:
    name: danyuan-application-web-vue-adminLTE
eureka:
  client:
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
      
zuul:
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 30000
  routes:
    crawler: 
      path: /crawler/**
      serviceId: danyuan-application-crawler-server
      
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000      