server:
  port: 82
spring:
  application:
    name: danyuan-application-getway-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
security:
  oauth2:
    client:
      access-token-uri: http://localhost:95/oauth2/oauth/token
      user-authorization-uri: http://localhost:95/oauth2/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:95/oauth2/user
      prefer-token-info: false
      
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    crawler:
      path: /crawler/**
      serviceId: danyuan-application-crawler-server
    dbms:
      path: /dbms/**
      serviceId: danyuan-application-dbms-server
    oauth2:
      path: /oauth2/**
      serviceId: danyuan-application-oauth2-server
      
    python:
      path: /python/**
      serviceId: danyuan-application-sidecar-server
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000