server:
  port: 82
spring:
  application:
    name: danyuan-application-zuul-server  devtools:    restart:      enabled: false
  thymeleaf:    cache: false  main:
    allow-bean-definition-overriding: true
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
      
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
# 自定义服务登录    
security:  
  oauth2:
    sso:
      # 登录回调路径
      loginPath: /index
    client:
      access-token-uri: http://localhost:8800/oauth2/oauth/token
      user-authorization-uri: http://localhost:8800/oauth2/oauth/authorize
      client-id: wth
      client-secret: wth
      #pre-established-redirect-uri: http://localhost:82/index
      #grant-type: password
      #scope: read
      #tokenName: oauth_token
      #authenticationScheme: query
      #clientAuthenticationScheme: form
    resource:
      #userInfoUri: http://localhost:8800/oauth2/user
      jwt:
        key-uri: http://localhost:8800/oauth2/oauth/token_key
    authorization:
      check-token-access: http://localhost:8800/oauth2/oauth/check_token
#  basic:
#    enabled: false
#      user-info-uri: http://localhost:8800/user
#      prefer-token-info: false
      
      

#  使用github 提供的登录
#security:
#  user:
#    password: user  # 直接登录时的密码
#  ignored: /
#  sessions: never   # session策略
#  oauth2:
#    sso:
#      loginPath: /login   # 登录路径
#    client:
#      clientId: 922cb28064e15219957b
#      clientSecret: 775d7f9f391916f6007ac8a89bba9a4ba1049417
#      accessTokenUri: https://github.com/login/oauth/access_token
#      userAuthorizationUri: https://github.com/login/oauth/authorize
#    resource:
#      userInfoUri: https://api.github.com/user
#      preferTokenInfo: false

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    crawler:
      path: /crawler/**
      serviceId: danyuan-application-crawler-server
    dbms:
      path: /dbms/**
      serviceId: danyuan-application-dbms-server
    rbac:
      path: /rbac/**
      serviceId: danyuan-application-rbac-server
    oauth2:
      path: /oauth2/**
      serviceId: danyuan-application-oauth2-server
      sensitiveHeaders:
      strip-prefix: false
    python:
      path: /python/**
      serviceId: danyuan-application-sidecar-server
  add-host-header: true
  add-proxy-headers: true
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

# hystrix 时间要是ribbon的三倍
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 900000
  