# \u5e94\u7528\u7aef\u53e3\u914d\u7f6e
server:
  port: 8761

spring:
  application:
    name: danyuan-application-crawler-server
    
 
eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/