# \u5e94\u7528\u7aef\u53e3\u914d\u7f6e
server:
  port: 80
spring:
  application:
    name: danyuan-application-web-vue-adminLTE
eureka:
  client:
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    
ribbon:  
  ReadTimeout: 3000
  ConnectTimeout: 3000    
zuul:
  host:
      connect-timeout-millis: 3000
      socket-timeout-millis: 3000
  ignored-services: '*'
  routes:
    danyuan-application-crawler-server: /crawler/**
      
        
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000        