server:
  port: 8800
  servlet:    context-path: /oauth2
spring:
  application:
    name: danyuan-application-oauth2-server
  datasource:
    url: jdbc:mysql:///application?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    username: root
    password: 514840279@qq.com
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    enabled: true
    mode: HTML5
    encoding: UTF-8
    servlet:      content-type: text/html; charset=utf-8    
  main:    allow-bean-definition-overriding: true

security:
#  user:
#    password: 123
  oauth2:
#    client:
#      client-id: wth
#      client-secret: wth
#    resource:
#      filter-order: 3
    authorization:
      check-token-access: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    org.danyuan: DEBUG
    
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
  instance:
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}${server.servlet.context-path}
  
  
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  add-host-header: true
  add-proxy-headers: true
  routes:
    rbac:
      path: /rbac/**
      serviceId: danyuan-application-rbac-server
      
feign:
  compression:
    request:
      enabled: true #开启请求压缩功能
      mime-types: text/xml;application/xml;application/json #指定压缩请求数据类型
      min-request-size: 2048 #如果传输超过该字节，就对其进行压缩
    response:
      enabled: true #开启响应压缩功能
      
      #Fegin 连接超时
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  
# hystrix 时间要是ribbon的三倍
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 900000
                