server:
  port: 9000
spring:
  application:
    name: danyuan-application-sidecar-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://wth:wth@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

sidecar:
  port: 3000
  health-uri: http://127.0.0.1:3000/health